import { useState } from "react";
import { useUserAuth } from "@/hooks/use-auth";
import { useListUserScripts, useProtectScript, useDeleteScript } from "@workspace/api-client-react";
import { useQueryClient } from "@tanstack/react-query";
import { useLocation } from "wouter";
import { CyberCard, CyberButton, CyberInput, CyberTextarea } from "@/components/ui/cyber-ui";
import { LogOut, UploadCloud, Terminal, AlertTriangle, Copy, Trash2 } from "lucide-react";
import { useToast } from "@/hooks/use-toast";
import { format } from "date-fns";

export default function UserDashboard() {
  const { key, isAuthenticated, logout, authHeaders } = useUserAuth();
  const [, setLocation] = useLocation();
  const { toast } = useToast();
  const queryClient = useQueryClient();

  if (!isAuthenticated || !key) {
    setLocation("/dashboard");
    return null;
  }

  // Passing the headers in request configuration generated by Orval
  const { data: scriptsData, isLoading: scriptsLoading } = useListUserScripts({ request: authHeaders });

  const [form, setForm] = useState({ name: "", content: "" });
  const [generatedResult, setGeneratedResult] = useState<{ id: string, loadstringCode: string } | null>(null);

  const protectMutation = useProtectScript({
    request: authHeaders,
    mutation: {
      onSuccess: (res) => {
        queryClient.invalidateQueries({ queryKey: ['/api/user/scripts'] });
        setGeneratedResult({ id: res.id, loadstringCode: res.loadstringCode });
        setForm({ name: "", content: "" });
        toast({ title: "PROTECTION APPLIED", description: "Script successfully obfuscated and stored." });
      },
      onError: () => {
        toast({ title: "PROTECTION FAILED", description: "License might be expired or invalid.", variant: "destructive" });
      }
    }
  });

  const deleteMutation = useDeleteScript({
    request: authHeaders,
    mutation: {
      onSuccess: () => {
        queryClient.invalidateQueries({ queryKey: ['/api/user/scripts'] });
        toast({ title: "SCRIPT DELETED", description: "Payload removed from secure registry." });
      }
    }
  });

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    protectMutation.mutate({ data: form });
  };

  const copyToClipboard = (text: string) => {
    navigator.clipboard.writeText(text);
    toast({ title: "COPIED", description: "Loadstring copied to clipboard" });
  };

  // Decode JWT/Key info typically handled by backend, but we'll show UI placeholders
  // The actual expiry is enforced by the backend on every request.

  return (
    <div className="min-h-screen bg-background text-foreground p-4 md:p-8 scanlines relative">
      <div className="absolute inset-0 bg-gradient-to-b from-primary/5 via-background to-background pointer-events-none -z-10"></div>
      
      <div className="max-w-7xl mx-auto space-y-8">
        {/* Header */}
        <header className="flex flex-col md:flex-row items-center justify-between gap-4 border-b border-primary/30 pb-6">
          <div className="flex items-center gap-4">
            <div className="w-12 h-12 bg-primary/10 border border-primary/50 flex items-center justify-center rounded">
              <Terminal className="w-6 h-6 text-primary" />
            </div>
            <div>
              <h1 className="text-3xl font-display font-bold text-white neon-text">VIREON <span className="text-xs text-primary border border-primary px-2 py-1 rounded ml-2 align-middle">PREMIUM</span></h1>
              <p className="text-sm font-mono text-muted-foreground mt-1">SECURE_DEVELOPMENT_ENVIRONMENT</p>
            </div>
          </div>
          <CyberButton variant="outline" onClick={logout} className="border-destructive/30 text-destructive hover:bg-destructive hover:text-white">
            <LogOut className="w-4 h-4 mr-2 inline" /> DISCONNECT
          </CyberButton>
        </header>

        {/* Expiry Warning */}
        <div className="p-4 bg-destructive/10 border border-destructive/50 rounded flex items-start gap-3">
          <AlertTriangle className="w-5 h-5 text-destructive shrink-0 mt-0.5" />
          <div>
            <p className="text-destructive font-bold text-sm uppercase">Peringatan / Warning</p>
            <p className="text-sm text-destructive/80 mt-1">
              Jika premium habis, script otomatis berhenti berfungsi. Hubungi admin untuk perpanjang. 
              (If premium expires, scripts stop working automatically. Contact admin to renew).
            </p>
          </div>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
          {/* Upload Section */}
          <CyberCard className="border-secondary/30 h-fit">
            <h2 className="text-xl font-bold text-secondary mb-6 flex items-center gap-2">
              <UploadCloud className="w-5 h-5" /> 📤 UPLOAD_SCRIPT
            </h2>
            <form onSubmit={handleSubmit} className="space-y-4">
              <div>
                <label className="text-xs text-muted-foreground uppercase mb-1 block">Payload Name</label>
                <CyberInput 
                  value={form.name}
                  onChange={(e) => setForm({...form, name: e.target.value})}
                  placeholder="e.g. AutoFarm_V1"
                  required
                  className="border-secondary/30 focus:border-secondary focus:ring-secondary text-secondary"
                />
              </div>
              <div>
                <label className="text-xs text-muted-foreground uppercase mb-1 block">Raw Lua Source</label>
                <CyberTextarea 
                  value={form.content}
                  onChange={(e) => setForm({...form, content: e.target.value})}
                  placeholder="Paste script .lua kamu di sini..."
                  required
                  className="h-48 border-secondary/30 focus:border-secondary focus:ring-secondary text-green-400 font-mono"
                />
              </div>
              <CyberButton 
                type="submit" 
                disabled={protectMutation.isPending} 
                className="w-full !border-secondary !text-secondary before:!bg-secondary hover:!text-white"
              >
                {protectMutation.isPending ? "ENCRYPTING..." : "PROTECT & GENERATE LINK"}
              </CyberButton>
            </form>
          </CyberCard>

          {/* Generated Result & History */}
          <div className="space-y-8">
            {generatedResult && (
              <CyberCard className="border-green-500/50 shadow-[0_0_20px_rgba(34,197,94,0.1)]">
                <h2 className="text-xl font-bold text-green-400 mb-4">🔑 YOUR_SCRIPT_KEY</h2>
                <div className="bg-black p-4 rounded border border-dashed border-green-500/50 mb-4 font-mono text-sm overflow-x-auto relative group">
                  <pre className="text-yellow-400">
                    <span className="text-pink-500">script_key</span>=<span className="text-green-300">"{key}"</span>;<br/>
                    <span className="text-blue-400">loadstring</span>(<span className="text-white">game</span>:<span className="text-blue-400">HttpGet</span>(<span className="text-green-300">"{window.location.origin}/api/get?key={key}&script_id={generatedResult.id}"</span>))()
                  </pre>
                  <button 
                    onClick={() => copyToClipboard(`script_key="${key}";\nloadstring(game:HttpGet("${window.location.origin}/api/get?key=${key}&script_id=${generatedResult.id}"))()`)}
                    className="absolute top-2 right-2 p-2 bg-green-500/20 text-green-400 hover:bg-green-500 hover:text-black transition-colors rounded opacity-0 group-hover:opacity-100"
                  >
                    <Copy className="w-4 h-4" />
                  </button>
                </div>
              </CyberCard>
            )}

            <CyberCard>
              <h2 className="text-xl font-bold text-primary mb-6 flex items-center gap-2">
                <Terminal className="w-5 h-5" /> ACTIVE_PAYLOADS
              </h2>
              {scriptsLoading ? (
                <div className="animate-pulse text-primary">SYNCING_WITH_SERVER...</div>
              ) : (
                <div className="space-y-4">
                  {scriptsData?.scripts?.map((script) => (
                    <div key={script.id} className="border border-primary/20 bg-primary/5 p-4 rounded group relative">
                      <div className="flex justify-between items-start mb-2">
                        <div>
                          <h3 className="font-bold text-white text-lg">{script.name}</h3>
                          <p className="text-xs text-muted-foreground font-mono">Created: {format(new Date(script.createdAt), "yyyy-MM-dd")}</p>
                        </div>
                        <button 
                          onClick={() => deleteMutation.mutate({ scriptId: script.id })}
                          className="text-destructive hover:text-white hover:bg-destructive p-2 rounded transition-colors"
                        >
                          <Trash2 className="w-4 h-4" />
                        </button>
                      </div>
                      <div className="mt-3 flex gap-2">
                        <CyberButton 
                          variant="outline" 
                          className="w-full py-1 text-xs"
                          onClick={() => copyToClipboard(`script_key="${key}";\nloadstring(game:HttpGet("${window.location.origin}/api/get?key=${key}&script_id=${script.id}"))()`)}
                        >
                          <Copy className="w-3 h-3 mr-2 inline" /> COPY_LOADSTRING
                        </CyberButton>
                      </div>
                    </div>
                  ))}
                  {(!scriptsData?.scripts || scriptsData.scripts.length === 0) && (
                    <div className="text-center py-8 text-muted-foreground border border-dashed border-primary/20 rounded">
                      NO_SCRIPTS_FOUND
                    </div>
                  )}
                </div>
              )}
            </CyberCard>
          </div>
        </div>
      </div>
    </div>
  );
}
